#pragma once

const char* player_anim_1() {
    return
        R"(
<?xml version="1.0"?>
<data>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/front/dotchara1_ver3_front1.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/left/dotchara1_ver3_left1.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/right/dotchara1_ver3_right1.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/walk/back/dotchara1_ver3_back1.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/run/front/dotchara1_ver3_front_run1.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/run/front/dotchara1_ver3_front_run2.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/run/front/dotchara1_ver3_front_run3.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/run/front/dotchara1_ver3_front_run4.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/run/left/dotchara1_ver3_left_run1.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/run/left/dotchara1_ver3_left_run2.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/run/left/dotchara1_ver3_left_run3.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/run/left/dotchara1_ver3_left_run4.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/run/right/dotchara1_ver3_right_run1.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/run/right/dotchara1_ver3_right_run2.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/run/right/dotchara1_ver3_right_run3.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/run/right/dotchara1_ver3_right_run4.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/run/back/dotchara1_ver3_back_run1.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/run/back/dotchara1_ver3_back_run2.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/run/back/dotchara1_ver3_back_run3.png</filename>
            <duration>200</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/run/back/dotchara1_ver3_back_run4.png</filename>
            <duration>200</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/scythe/front/dotchara1_ver3_front_scythe1.png</filename>
            <duration>500</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/scythe/front/dotchara1_ver3_front_scythe4.png</filename>
            <duration>50</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/scythe/front/dotchara1_ver3_front_scythe5.png</filename>
            <duration>450</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/scythe/left/dotchara1_ver3_left_scythe1.png</filename>
            <duration>500</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/scythe/left/dotchara1_ver3_left_scythe4.png</filename>
            <duration>50</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/scythe/left/dotchara1_ver3_left_scythe5.png</filename>
            <duration>450</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/scythe/right/dotchara1_ver3_right_scythe1.png</filename>
            <duration>500</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/scythe/right/dotchara1_ver3_right_scythe4.png</filename>
            <duration>50</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/scythe/right/dotchara1_ver3_right_scythe5.png</filename>
            <duration>450</duration>
        </frame>
    </animation>
    <animation>
        <frame>
            <filename>./resource/imgs/scythe/back/dotchara1_ver3_back_scythe1.png</filename>
            <duration>500</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/scythe/back/dotchara1_ver3_back_scythe4.png</filename>
            <duration>50</duration>
        </frame>
        <frame>
            <filename>./resource/imgs/scythe/back/dotchara1_ver3_back_scythe5.png</filename>
            <duration>450</duration>
        </frame>
    </animation>
</data>
)";
}
